In [6]:
import numpy as np
import gymnasium as gym

env=gym.make("FrozenLake-v1",is_slippery=False)
state, info = env.reset()

n_states = env.observation_space.n 
n_actions = env.action_space.n
Q = np.zeros((n_states,n_actions))

eps_start = 1
eps_decay = 0.0001
eps_min = 0.01

def epsilon(episode):
    a = max(eps_min, eps_start - eps_decay*episode)
    return a 

n_iterations = 10000
alpha = 0.8
gamma = 0.95
for i in range(n_iterations):
    state, info = env.reset()
    terminated = False
    truncated = False
    while not (terminated or truncated):
        if epsilon(i) > np.random.rand() :
            action = env.action_space.sample()
        else: 
            action = Q[state].argmax()
        next_state, reward, terminated, truncated, info = env.step(action)
        Q[state,action] = Q[state,action] + alpha*(reward + gamma*Q[next_state].max()-Q[state,action])
        state = next_state
print(Q)

[[0.73509189 0.77378094 0.77378094 0.73509189]
 [0.73509189 0.         0.81450625 0.77378094]
 [0.77378094 0.857375   0.77378094 0.81450625]
 [0.81450625 0.         0.77378094 0.77378094]
 [0.77378094 0.81450625 0.         0.73509189]
 [0.         0.         0.         0.        ]
 [0.         0.9025     0.         0.81450625]
 [0.         0.         0.         0.        ]
 [0.81450625 0.         0.857375   0.77378094]
 [0.81450625 0.9025     0.9025     0.        ]
 [0.857375   0.95       0.         0.857375  ]
 [0.         0.         0.         0.        ]
 [0.         0.         0.         0.        ]
 [0.         0.9025     0.95       0.857375  ]
 [0.9025     0.95       1.         0.9025    ]
 [0.         0.         0.         0.        ]]


In [18]:
test_env=gym.make("FrozenLake-v1",is_slippery=False)
state, info = test_env.reset()

terminated=False
truncated=False
total_reward=0
while not (truncated or terminated):
    action = Q[state].argmax()
    state,reward,terminated,truncated,info = test_env.step(action)
    total_reward+=reward
print(total_reward)


1
