# NumPy Exercises

Now that we've learned about NumPy let's test your knowledge. We'll start off with a few simple tasks, and then you'll be asked some more complicated questions.

#### Import NumPy as np

In [ ]:
import numpy as np

#### Create an array of 10 zeros

In [ ]:
arr = np.zeros((10))

#### Create an array of 10 ones

In [ ]:
arr = np.ones((10))

#### Create an array of 10 fives

In [ ]:
arr = np.full((10), 5)

#### Create an array of the integers from 10 to 50

In [ ]:
arr = np.arange(10, 51, 1)

#### Create an array of all the even integers from 10 to 50

In [ ]:
arr = np.arange(10, 51, 2)

#### Create a 3x3 matrix with values ranging from 0 to 8

In [ ]:
arr = np.arange(0, 9)
arr.reshape((3, 3))

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

#### Create a 3x3 identity matrix

In [ ]:
arr = np.identity(3)

#### Use NumPy to generate a random number between 0 and 1

In [ ]:
arr = np.random.rand(1)

#### Use NumPy to generate an array of 25 random numbers sampled from a standard normal distribution

In [ ]:
arr = np.random.normal(0, 1, 25)

#### Create the following matrix:

In [ ]:
arr = np.arange(0.01, 1.01, 0.01).reshape((10, 10))

#### Create an array of 20 linearly spaced points between 0 and 1:

In [ ]:
arr = np.linspace(0, 1, 21)

## Numpy Indexing and Selection

Now you will be given a few matrices, and be asked to replicate the resulting matrix outputs:

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

array([[12, 13, 14, 15],
       [17, 18, 19, 20],
       [22, 23, 24, 25]])

20

array([[ 2],
       [ 7],
       [12]])

array([21, 22, 23, 24, 25])

array([[16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

# Great Job!