# Training

In [2]:
import gymnasium as gym
import numpy as np

In [ ]:
a=0.8 #learning rate
g=0.95 #discount factor

rng=np.random.default_rng() #random number generator

env=gym.make(
    'FrozenLake-v1',
    desc=None,
    map_name="4x4",
    is_slippery=False,
    reward_schedule=(10,-5,0),
)

def select_action(Q,S,e):
    x=rng.random()
    if x<e:
        return rng.integers(low=0,high=4)
    else:
        return Q[S].argmax()

Q=np.random.randn(64).reshape((16,4)) #make a arbitrary Q table and store it as a 16x4 array
Q[15]=[0,0,0,0]
print("Initial Q table:",Q)

state,info=env.reset()
run=True
n=0

while n<10000:
    while run:
        e=max(0.01,0.999**n) # eps_start=1, eps_end=0.01, eps_decay=0.999, epsilon = max(eps_end, eps_start*(eps_decay)**(episode_number))
        action = select_action(Q,state,e)
        prev_state=state
        state, reward, terminated, truncated, info = env.step(action)
        q=Q[state].max()
        Q[prev_state][action]+=a*(reward+g*q-Q[prev_state][action]) # Q learning implementation

        if truncated or terminated:
            state, info=env.reset()
            run=False
    n+=1
    run=True

print("Final Q table:",(Q))
env.close()

Initial Q table: [[ 0.93761173  1.03190674 -0.34911835 -0.27341211]
 [-1.58269615  1.85745956  0.01164501 -0.58940133]
 [-0.82743845 -0.53487351  0.00818297  0.2656737 ]
 [ 0.03530733 -1.4861868   0.11047334 -0.03284743]
 [ 0.09081534 -0.54011704  1.20113396 -1.7136453 ]
 [-0.75309776  1.93891147  0.56151487  0.95065349]
 [-0.434802    0.13074478  0.48886974 -0.59063403]
 [-0.03655272  1.34224428  0.94643352 -0.86591202]
 [-1.06613085  2.04626752 -0.48494637 -1.40385192]
 [ 0.88953151 -0.13372451 -0.82145143 -0.36214895]
 [ 1.20594471 -2.11878403 -0.94016621 -1.66436867]
 [ 0.64701079 -0.39451895  0.48522483 -0.53380254]
 [-1.21233086  0.81499479  0.59793537  0.34495765]
 [ 0.22123134 -1.38470268  1.01223443  1.41427946]
 [-0.32363901  0.30533926 -0.32245769 -1.2673961 ]
 [ 0.          0.          0.          0.        ]]
Final Q table: [[ 7.35091891  7.73780937  7.73780937  7.35091891]
 [ 7.35091891 -3.1580341   8.1450625   7.73780937]
 [ 7.73780937  8.57375     7.73780937  8.1450625 

# Testing

In [8]:
env1=gym.make(
    'FrozenLake-v1',
    desc=None,
    map_name="4x4",
    is_slippery=False,
    reward_schedule=(10, -5, 0),
    render_mode="human"
)

run=True
state, info=env1.reset()
while run:
    action =  Q[state].argmax()
    state, reward, terminated, truncated, info = env1.step(action)

    if truncated or terminated:
        state, info=env1.reset()
        run=False
env1.close()