# NumPy Exercises

Now that we've learned about NumPy let's test your knowledge. We'll start off with a few simple tasks, and then you'll be asked some more complicated questions.

#### Import NumPy as np

In [ ]:
import numpy as np

#### Create an array of 10 zeros

In [ ]:
arr = np.array([0, 0, 0, 0, 0, 0, 0, 0, 0])

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

#### Create an array of 10 ones

In [ ]:
arr=np.array([])
for i in range(0, 10):
    arr=np.append(arr, 1)
print(arr)

[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]


#### Create an array of 10 fives

In [ ]:
arr=np.array([])
for i in range(0, 10):
    arr=np.append(arr, 5)
print(arr)

[5. 5. 5. 5. 5. 5. 5. 5. 5. 5.]


#### Create an array of the integers from 10 to 50

In [ ]:
arr=np.array([])
for i in range(9, 50):
    arr=np.append(arr, i+1)
print(arr)

[10. 11. 12. 13. 14. 15. 16. 17. 18. 19. 20. 21. 22. 23. 24. 25. 26. 27.
 28. 29. 30. 31. 32. 33. 34. 35. 36. 37. 38. 39. 40. 41. 42. 43. 44. 45.
 46. 47. 48. 49. 50.]


#### Create an array of all the even integers from 10 to 50

In [ ]:
arr=np.array([])
for i in range(9, 50):
  if (i+1)%2==0 :
    arr=np.append(arr, i+1)
print(arr)

[10. 12. 14. 16. 18. 20. 22. 24. 26. 28. 30. 32. 34. 36. 38. 40. 42. 44.
 46. 48. 50.]


#### Create a 3x3 matrix with values ranging from 0 to 8

In [ ]:
matrix = np.arange(9).reshape(3, 3)
print(matrix)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


#### Create a 3x3 identity matrix

In [ ]:
print(np.eye(3))

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


#### Use NumPy to generate a random number between 0 and 1

In [ ]:
print(np.random.rand(1))

[0.33917367]


#### Use NumPy to generate an array of 25 random numbers sampled from a standard normal distribution

In [ ]:
print(np.random.randn(25))

[-1.46838563  2.25325959 -0.84224398  0.20168669 -1.26444466  1.01840053
  1.04905095 -0.38964351 -0.4160085  -1.60303199  0.5989315   0.43646282
  0.04421467 -0.15999468 -0.55219031 -1.38889738  0.76927686  0.47805368
  0.23602932  0.49238701  0.12651685 -1.07442341  1.14277846  0.22617586
 -1.94770071]


#### Create the following matrix:

#### Create an array of 20 linearly spaced points between 0 and 1:

In [ ]:
print("array("+str(np.linspace(0, 1, 20))+")")

array([0.         0.05263158 0.10526316 0.15789474 0.21052632 0.26315789
 0.31578947 0.36842105 0.42105263 0.47368421 0.52631579 0.57894737
 0.63157895 0.68421053 0.73684211 0.78947368 0.84210526 0.89473684
 0.94736842 1.        ])


## Numpy Indexing and Selection

Now you will be given a few matrices, and be asked to replicate the resulting matrix outputs:

In [ ]:
print(np.arange(1, 26).reshape(5, 5))

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]]


In [ ]:
print(np.arange(11, 26).reshape(3, 5))

[[11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]]


In [ ]:
#I think something is missing

20

In [ ]:
arr=np.array([[ 2], [ 7], [12]])
print(arr)


[[ 2]
 [ 7]
 [12]]


In [ ]:
print(np.arange(21, 26))

[21 22 23 24 25]


In [ ]:
print(np.arange(16, 26).reshape(2, 5))

[[16 17 18 19 20]
 [21 22 23 24 25]]


# Great Job!